# Application Config
spring:
     application:
          name: ms-client-management
     # Spring Cloud Config
     cloud:
          config:
               uri: http://localhost:8888
          
server:
     port: 8001
